name: Pixl
main: hackhalo2.creative.Pixl.Pixl
version: 1.5
author: HACKhalo2
commands:
    pixl:
        description: The default command for Pixl
        usage: /<command>
        example: /<command> | Show version info and help
        example: /<command> toggle | Toggle on/off
        example: /<command> set <value> | hard-set the byte value
        example: /<command> clear | clear the value set by the set command