name: Pixl
main: com.hackhalo2.creative.Pixl
version: 1.7.2
author: HACKhalo2
commands:
    pixl:
        description: The default command for Pixl
        usage: /<command>
        example: /<command> | Toggle PixlArt on/off
        example: /<command> help | Help Menu
        example: /<command> break | Toggle PixlBreak on/off
        example: /<command> set <value> | hard-set the byte value
        example: /<command> clear | clear the value set by the set command
